name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout do código
        uses: actions/checkout@v3

      - name: ☕ Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 🧪 Build com Maven
        run: mvn clean install -DskipTests

      - name: 📦 Obter versão do projeto (pom.xml)
        id: project_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: 🐳 Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 🏗️ Build da imagem Docker
        run: docker build -t torresbento/tbmt-cadastro-de-pessoas:${{ steps.project_version.outputs.version }} .

      - name: 📤 Push para Docker Hub
        run: docker push torresbento/tbmt-cadastro-de-pessoas:${{ steps.project_version.outputs.version }}

      - name: 🚀 Verificar segredo REMOTE_HOST
        id: check_remote_host
        run: |
          if [ -z "${{ secrets.REMOTE_HOST }}" ]; then
            echo "ERROR: REMOTE_HOST not set!"
            exit 1
          else
            echo "REMOTE_HOST is set to ${REMOTE_HOST}"
          fi

      - name: 🚀 Deploy no servidor via SSH
        if: success()
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.REMOTE_PORT }}  # se não for 22, senão pode remover
          script: |
            echo "⛔ Parando container antigo (se existir)..."
            sudo docker stop cadastro-pessoas || true

            echo "🗑️ Removendo container antigo (se existir)..."
            sudo docker rm cadastro-pessoas || true

            echo "🧹 Removendo imagem antiga (se existir)..."
            sudo docker image prune -a -f --filter "label=project=cadastro-pessoas" || true

            echo "⬇️ Baixando nova imagem..."
            sudo docker pull torresbento/tbmt-cadastro-de-pessoas:${{ steps.project_version.outputs.version }}

            echo "🌐 Garantindo que a rede Docker personalizada exista com o subnet correto..."
            # Verificando se a rede tbmt-rede-docker tem o subnet correto
            if sudo docker network inspect tbmt-rede-docker | grep -q '"Subnet": "172.18.0.0/16"'; then
              echo "Rede tbmt-rede-docker existe com o subnet correto."
            else
              echo "Rede tbmt-rede-docker não tem o subnet correto. Removendo e recriando..."
              sudo docker network rm tbmt-rede-docker || true
              sudo docker network create --driver bridge --subnet 172.18.0.0/16 tbmt-rede-docker
            fi

            echo "🏃 Subindo novo container com IP fixo..."
            sudo docker run -d --name cadastro-pessoas \
              --label project=cadastro-pessoas \
              --network tbmt-rede-docker \
              --ip 172.18.0.90 \
              -p 9090:9090 \
              torresbento/tbmt-cadastro-de-pessoas:${{ steps.project_version.outputs.version }}
